version: '3.9'

services:

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2316
      POSTGRES_DB: psy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  django_app:
    build:
      context: ./psy
    container_name: django_app
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - mynetwork


#  telegram_bot:
#    build:
#      context: ./psy/telegram_bot_app
#    container_name: telegram_bot
#    env_file:
#      - .env
#    volumes:
#      - ./telegram_bot_app:/app
#    depends_on:
#      - django_app
#    networks:
#      - mynetwork

networks:
  mynetwork:
      driver: bridge

volumes:
  postgres_data: