# Generated by Django 4.2 on 2023-07-17 15:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва сертифікату')),
                ('issuing_organization', models.CharField(max_length=255, verbose_name='Видавник/Організація')),
                ('image', models.ImageField(upload_to='certificate_images/', verbose_name='Фото сертифікату')),
                ('date', models.DateField(verbose_name='Коли виданий')),
                ('link', models.CharField(max_length=100, null=True, verbose_name='Посилання на сертифікат')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Сертифікат',
                'verbose_name_plural': 'Сертифікати',
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва диплому')),
                ('date', models.DateField(verbose_name='Коли виданий')),
                ('image', models.ImageField(upload_to='diploma_images/', verbose_name='Фото диплому')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Дипломи',
                'verbose_name_plural': 'Дипломи',
            },
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Про психолога')),
                ('contact_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None, verbose_name='Номери телефонів')),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(upload_to='psychologist_profiles/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificates', models.ManyToManyField(to='psychologist_app.certificate', verbose_name='Сертифікати')),
                ('diplomas', models.ManyToManyField(to='psychologist_app.diploma', verbose_name='Дипломи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Психолог',
                'verbose_name_plural': 'Психолог',
            },
        ),
    ]
