# Generated by Django 4.2 on 2023-08-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist_app', '0002_contentitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва ознаки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contentitems',
            name='sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psychologist_app.sign', verbose_name='Ознака'),
        ),
    ]
