# Generated by Django 4.2 on 2023-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist_app', '0003_sign_contentitems_sign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentitems',
            options={'ordering': ['created_at'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Контенти'},
        ),
        migrations.AlterModelOptions(
            name='sign',
            options={'ordering': ['title'], 'verbose_name': 'Ознака', 'verbose_name_plural': 'Ознаки'},
        ),
        migrations.AddField(
            model_name='psychologist',
            name='facebook',
            field=models.CharField(max_length=255, null=True, verbose_name='Фейсбук'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='instagram',
            field=models.CharField(max_length=255, null=True, verbose_name='Інстаграм'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='telegram',
            field=models.CharField(max_length=20, null=True, verbose_name='Телеграм'),
        ),
    ]
