# Generated by Django 4.2 on 2023-10-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist_app', '0005_contentitems_icons_alter_contentitems_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='certificates',
            field=models.ManyToManyField(blank=True, null=True, to='psychologist_app.certificate', verbose_name='Сертифікати'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='diplomas',
            field=models.ManyToManyField(blank=True, null=True, to='psychologist_app.diploma', verbose_name='Дипломи'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фейсбук'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Інстаграм'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='telegram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телеграм'),
        ),
    ]
