# Generated by Django 4.2 on 2023-11-12 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist_app', '0007_diploma_issuing_organization_diploma_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='contact_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None, verbose_name='Номери телефонів'),
        ),
    ]
