# Generated by Django 4.2 on 2023-09-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_token', models.CharField(max_length=255, verbose_name='Токен Телеграм')),
                ('chat_id', models.CharField(max_length=50, verbose_name='id Чату')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='id Користувача')),
                ('webhook_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса веб-хука')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Телеграм Бот',
                'verbose_name_plural': 'Телеграм Боти',
                'ordering': ['created_at'],
            },
        ),
    ]
