# Generated by Django 4.2 on 2023-10-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_at_alter_post_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='topic_images/', verbose_name='Зображення'),
        ),
    ]
