# Generated by Django 4.2 on 2023-10-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_topic_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='topic_images/', verbose_name='Зображення'),
        ),
    ]
