# Generated by Django 4.2 on 2023-10-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_topic_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Опис теми'),
        ),
    ]
