# Generated by Django 4.2 on 2023-10-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_topic_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='color',
            field=models.CharField(choices=[('style1', 'Рожевий'), ('style2', 'Блакитний'), ('style3', 'Бірюзовий'), ('style4', 'Малиновий'), ('style5', 'Фіолетовий'), ('style6', 'Синій'), ('none', 'Прозорий')], default='pink', max_length=20),
        ),
    ]
