# Generated by Django 4.2 on 2023-10-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist_app', '0004_alter_contentitems_options_alter_sign_options_and_more'),
        ('blog', '0009_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='psychologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psychologist_app.psychologist', verbose_name='Автор посту'),
        ),
    ]
