# Generated by Django 4.2 on 2023-07-17 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('issue_description', models.TextField(verbose_name='Інформація про клієнта')),
                ('profile_picture', models.ImageField(upload_to='client_profiles/', verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Клієнти',
                'verbose_name_plural': 'Клієнти',
            },
        ),
        migrations.CreateModel(
            name='SessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Дата сессії')),
                ('session_time', models.TimeField(verbose_name='Час сессії')),
                ('status', models.CharField(choices=[('pending_confirmation', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('canceled', 'Скасовано'), ('rescheduled', 'Перенесено'), ('completed', 'Завершено')], default='pending_confirmation', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Cесія',
                'verbose_name_plural': 'Сесії',
            },
        ),
    ]
