# Generated by Django 4.2 on 2023-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrecord',
            name='session_time',
            field=models.TimeField(null=True, verbose_name='Час сессії'),
        ),
    ]
