# Generated by Django 4.2 on 2023-07-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_alter_sessionrecord_session_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionrecord',
            options={'verbose_name': 'Сесія', 'verbose_name_plural': 'Сесії'},
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='client_profiles/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='sessionrecord',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.client', verbose_name='Клієнт'),
        ),
    ]
