# Generated by Django 4.2 on 2023-07-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_alter_sessionrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='profile_picture',
        ),
    ]
