# Generated by Django 4.2 on 2023-07-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_remove_client_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Прізвище'),
        ),
    ]
