# Generated by Django 4.2 on 2023-07-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_sessionrecord_issue_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrecord',
            name='issue_description',
        ),
    ]
