# Generated by Django 4.2 on 2023-08-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_remove_sessionrecord_issue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='client_profiles/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='sessionrecord',
            name='session_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Час сессії'),
        ),
    ]
