## Dockerfile в telegram_bot_app
#FROM python:3.11.5
#
#WORKDIR /app
#
## Скопіюйте файл requirements.txt з кореня проекту
#COPY ../../requirements.txt /app/requirements.txt
#
#RUN pip install --no-cache-dir -r requirements.txt
#
#COPY . .
#
#CMD ["python", "bot.py"]
